name: 'playwright-report'
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  playwright:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
      - uses: actions/checkout@v3
      - uses: sidharthv96/playwright-report-action
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}